package com.packflow.app.order;

public enum OrderEventType {
    STOCK_SHORTAGE, PARTIAL_SHIPMENT_PLANNED, OUTBOUND_SHORTAGE,
    SUPPLEMENTAL_PLANNED, SHIPMENT_COMPLETED, SHIPMENT_CANCELLED,
    CUSTOMER_ACCEPTED_SHORTAGE, UNABLE_TO_DELIVER, FULFILLMENT_COMPLETED
}
