-- Consolidated schema as of Flyway V8 for NEW, EMPTY databases only.
-- Flyway uses B8 instead of executing V1..V8 on an empty database.
-- Existing databases continue to validate and retain the immutable V1..V8 history.
-- Demo users are created only by the local-profile application bootstrap, not by SQL.

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('SALES', 'WAREHOUSE', 'MANAGER')),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    token_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    unit VARCHAR(20) NOT NULL,
    safety_stock NUMERIC(18, 3) NOT NULL DEFAULT 0 CHECK (safety_stock >= 0),
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sales_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(50) NOT NULL UNIQUE,
    customer_name VARCHAR(150) NOT NULL,
    status VARCHAR(30) NOT NULL CHECK (status IN ('PENDING_CHECK', 'PENDING_OUTBOUND', 'COMPLETED', 'ABNORMAL', 'CANCELLED')),
    exception_reason TEXT,
    delivery_date DATE,
    abnormal_type VARCHAR(30),
    CONSTRAINT ck_sales_order_abnormal_type
        CHECK (status <> 'ABNORMAL' OR abnormal_type IS NOT NULL),
    created_by BIGINT NOT NULL REFERENCES app_user (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sales_order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES sales_order (id),
    product_id BIGINT NOT NULL REFERENCES product (id),
    ordered_quantity NUMERIC(18, 3) NOT NULL CHECK (ordered_quantity > 0),
    waived_quantity NUMERIC(18, 3) NOT NULL DEFAULT 0,
    CONSTRAINT ck_order_item_waived_quantity
        CHECK (waived_quantity >= 0 AND waived_quantity <= ordered_quantity),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_sales_order_item_order_product UNIQUE (order_id, product_id)
);

CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL UNIQUE REFERENCES product (id),
    quantity NUMERIC(18, 3) NOT NULL CHECK (quantity >= 0),
    version BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE inbound_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_no VARCHAR(50) NOT NULL UNIQUE,
    product_id BIGINT NOT NULL REFERENCES product (id),
    quantity NUMERIC(18, 3) NOT NULL CHECK (quantity > 0),
    remark VARCHAR(500),
    operator_id BIGINT NOT NULL REFERENCES app_user (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE outbound_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_no VARCHAR(50) NOT NULL UNIQUE,
    order_id BIGINT NOT NULL REFERENCES sales_order (id),
    order_item_id BIGINT NOT NULL REFERENCES sales_order_item (id),
    product_id BIGINT NOT NULL REFERENCES product (id),
    planned_quantity NUMERIC(18, 3) NOT NULL CHECK (planned_quantity > 0),
    planned_outbound_date DATE NOT NULL,
    shipment_type VARCHAR(20) NOT NULL DEFAULT 'INITIAL'
        CHECK (shipment_type IN ('INITIAL', 'SUPPLEMENTAL')),
    actual_quantity NUMERIC(18, 3) CHECK (actual_quantity IS NULL OR actual_quantity > 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'COMPLETED', 'CANCELLED')),
    difference_reason VARCHAR(500),
    operator_id BIGINT REFERENCES app_user (id),
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES sales_order(id),
    event_type VARCHAR(40) NOT NULL,
    description TEXT NOT NULL,
    operator_username VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_sales_order_status ON sales_order (status);
CREATE INDEX idx_sales_order_status_delivery_date ON sales_order (status, delivery_date);
CREATE INDEX idx_sales_order_created_by ON sales_order (created_by);
CREATE INDEX idx_sales_order_item_order_id ON sales_order_item (order_id);
CREATE INDEX idx_sales_order_item_product_id ON sales_order_item (product_id);
CREATE INDEX idx_inventory_product_id ON inventory (product_id);
CREATE INDEX idx_inbound_record_product_id ON inbound_record (product_id);
CREATE INDEX idx_inbound_record_operator_id ON inbound_record (operator_id);
CREATE INDEX idx_outbound_record_order_id ON outbound_record (order_id);
CREATE INDEX idx_outbound_record_order_item_id ON outbound_record (order_item_id);
CREATE INDEX idx_outbound_record_product_id ON outbound_record (product_id);
CREATE INDEX idx_outbound_record_operator_id ON outbound_record (operator_id);
CREATE INDEX idx_outbound_record_status ON outbound_record (status);
CREATE INDEX idx_outbound_record_status_planned_date
    ON outbound_record (status, planned_outbound_date);
CREATE INDEX idx_outbound_order_item_status
    ON outbound_record (order_item_id, status);
CREATE INDEX idx_order_event_order_time
    ON order_event (order_id, created_at, id);
