-- Allow more than one outbound shipment for the same order line.
-- The old schema declared order_item_id UNIQUE; remove only that uniqueness.
DO $$
DECLARE constraint_name text;
BEGIN
  FOR constraint_name IN
    SELECT c.conname
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY(c.conkey)
    WHERE t.relname = 'outbound_record' AND c.contype = 'u'
      AND array_length(c.conkey, 1) = 1 AND a.attname = 'order_item_id'
  LOOP
    EXECUTE format('ALTER TABLE outbound_record DROP CONSTRAINT %I', constraint_name);
  END LOOP;
END $$;

ALTER TABLE outbound_record ADD COLUMN shipment_type VARCHAR(20) NOT NULL DEFAULT 'INITIAL';
ALTER TABLE outbound_record ADD CONSTRAINT ck_outbound_shipment_type
    CHECK (shipment_type IN ('INITIAL', 'SUPPLEMENTAL'));
CREATE INDEX idx_outbound_order_item_status ON outbound_record (order_item_id, status);

ALTER TABLE sales_order_item ADD COLUMN waived_quantity NUMERIC(18,3) NOT NULL DEFAULT 0;
ALTER TABLE sales_order_item ADD CONSTRAINT ck_order_item_waived_quantity
    CHECK (waived_quantity >= 0 AND waived_quantity <= ordered_quantity);

CREATE TABLE order_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES sales_order(id),
    event_type VARCHAR(40) NOT NULL,
    description TEXT NOT NULL,
    operator_username VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_order_event_order_time ON order_event (order_id, created_at, id);
